server:
  port: 8761

#spring:
#  profiles:
#    active: pee1

eureka:
  instance:
    hostname: localhost
    instance-enabled-onit: true
    lease-expiration-duration-in-seconds: 90
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  #关闭自保护，剔除无效节点
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000