eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #高可用注册中心
#      defaultZone: http://peer1:8761/eureka/
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html

server:
  port: 8763
spring:
  application:
    name: service-hi

#spring boot关闭服务配置
endpoints:
  shutdown:
    enabled: true
    sensitive: false