eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#高可用注册中心
#      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/
server:
  port: 8762
spring:
  application:
    name: service-hi