eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8762/eureka/
#高可用注册中心
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/
server:
  port: 8764
spring:
  application:
    name: service-hi