eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8767
spring:
  application:
    name: service-zuul
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_zuul
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#zuul:
#  routes:
#    api-a:
#      path: /api-a/**
#      serviceId: service-ribbon
#    api-b:
#      path: /api-b/**
#      serviceId: service-feign